import { draftContentInputSchema, draftContentOutputSchema } from '@camello/shared/schemas';
import type { ModuleExecutionContext } from '@camello/shared/types';
import type { ModuleDefinition } from '../module-registry.js';
import { registerModule } from '../module-registry.js';

type Input = typeof draftContentInputSchema._output;
type Output = typeof draftContentOutputSchema._output;

const draftContentModule: ModuleDefinition<Input, Output> = {
  slug: 'draft_content',
  name: 'Draft Content',
  description:
    'Draft marketing content based on conversation context. Specify content type, topic, and key points. ' +
    'Call this when the customer or conversation triggers a content opportunity (social post, email, announcement).',
  category: 'marketing',
  riskTier: 'high',
  inputSchema: draftContentInputSchema,
  outputSchema: draftContentOutputSchema,

  async execute(input: Input, _ctx: ModuleExecutionContext): Promise<Output> {
    // The LLM response itself becomes the draft text — we capture the structured request.
    // The actual draft is generated by the LLM in the conversation response.
    const keyPointsSummary = input.key_points?.length
      ? input.key_points.join('; ')
      : input.topic;

    return {
      draft_text: `[Draft ${input.content_type}] Topic: ${input.topic}. Key points: ${keyPointsSummary}`,
      content_type: input.content_type,
      topic: input.topic,
      status: 'draft',
    };
  },

  formatForLLM: (output) =>
    `Content draft created (${output.content_type}): "${output.topic}". Status: ${output.status}. The owner will review and approve before publishing.`,
};

registerModule(draftContentModule as ModuleDefinition);
